[package]
name = "day_two"
version = "0.1.0"
authors = ["jpoo90 <jpoo90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
